=== pwalser75/json-xml-yaml-test/src/main/resources/Movie.schema.json
{
  "$schema": "http://json-schema.org/draft/2019-09/schema#",
  "definitions": {
    "name": {
      "type": "string",
      "pattern": "^\\p{Lu}\\p{Ll}+$"
    },
    "date": {
      "type": "string",
      "pattern": "\\d{4}-(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|[1-2][0-9]|3[0-1])"
    },
    "identifier": {
      "type": "string",
      "pattern": "^\\w+(-\\w+)*$"
    },
    "aspect-ratio": {
      "type": "string",
      "pattern": "^\\d+(\\.\\d+)?\\:\\d+(\\.\\d+)?$"
    },
    "duration": {
      "type": "string",
      "pattern": "^\\s*(?:(?:\\d+)\\s*w)?\\s*(?:(?:\\d+)\\s*d)?\\s*(?:(?:\\d+)\\s*h)?\\s*(?:(?:\\d+)\\s*m)?\\s*(?:(?:\\d+)\\s*s)?\\s*$"
    },
    "person": {
      "type": "object",
      "properties": {
        "firstName": {
          "$ref": "#/definitions/name"
        },
        "lastName": {
          "$ref": "#/definitions/name"
        },
        "dateOfBirth": {
          "$ref": "#/definitions/date"
        },
        "age": {
          "type": "integer",
          "minimum": 0
        }
      },
      "required": [
        "firstName",
        "lastName"
      ],
      "additionalProperties": true
    }
  },
  "id": "urn:jsonschema:ch:frostnova:test:jackson:test:util:domain:Movie",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "minLength": 2,
      "maxLength": 1000
    },
    "year": {
      "type": "integer",
      "minimum": 0
    },
    "genres": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/identifier"
      }
    },
    "aspect-ratio": {
      "$ref": "#/definitions/aspect-ratio"
    },
    "duration": {
      "$ref": "#/definitions/duration"
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "ratings": {
      "type": "object",
      "additionalProperties": {
        "type": "number",
        "minimum": 0
      }
    },
    "synopsis": {
      "type": "string"
    },
    "actors": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/person"
      }
    },
    "metadata": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": [
    "title",
    "year"
  ],
  "additionalProperties": false
}

=== pwalser75/json-xml-yaml-test/src/test/resources/test-data/movie-valid.json
{
  "title": "Blade Runner",
  "year": 1982,
  "genres": [
    "Sci-Fi",
    "Thriller"
  ],
  "aspect-ratio": "2.39:1",
  "created": "2020-06-15T10:08:25Z",
  "ratings": {
    "IMDB": 8.2,
    "Metacritic": 89.0
  },
  "synopsis": "A blade runner must pursue and terminate four replicants\n who stole a ship in space and have returned to Earth to find their creator.",
  "actors": [
    {
      "firstName": "Harrison",
      "lastName": "Ford",
      "dateOfBirth": "1942-07-13",
      "age": 77
    },
    {
      "firstName": "Rutger",
      "lastName": "Hauer",
      "dateOfBirth": "1944-01-23",
      "age": 76
    },
    {
      "firstName": "Sean",
      "lastName": "Young",
      "dateOfBirth": "1959-11-20",
      "age": 60
    }
  ],
  "metadata": {
    "director": "Ridley Scott",
    "release-date": "1982-06-25",
    "screenplay": "Hampton Fancher, David Webb Peoples"
  }
}
